export const emojiData = [
  {
    Number: 1,
    Code: "U+1F600",
    Browser: "😀",
    Sample: "😀",
    GMail: "😀",
    SB: "—",
    DCM: "—",
    KDDI: "—",
    CLDR_Short_Name: "grinning face",
  },
  {
    Number: 2,
    Code: "U+1F603",
    Browser: "😃",
    Sample: "😃",
    GMail: "😃",
    SB: "😃",
    DCM: "😃",
    KDDI: "😃",
    CLDR_Short_Name: "grinning face with big eyes",
  },
  {
    Number: 3,
    Code: "U+1F604",
    Browser: "😄",
    Sample: "😄",
    GMail: "😄",
    SB: "😄",
    DCM: "—",
    KDDI: "—",
    CLDR_Short_Name: "grinning face with smiling eyes",
  },
  {
    Number: 4,
    Code: "U+1F601",
    Browser: "😁",
    Sample: "😁",
    GMail: "😁",
    SB: "😁",
    DCM: "😁",
    KDDI: "😁",
    CLDR_Short_Name: "beaming face with smiling eyes",
  },
  {
    Number: 5,
    Code: "U+1F606",
    Browser: "😆",
    Sample: "😆",
    GMail: "😆",
    SB: "—",
    DCM: "😆",
    KDDI: "—",
    CLDR_Short_Name: "grinning squinting face",
  },
  {
    Number: 6,
    Code: "U+1F605",
    Browser: "😅",
    Sample: "😅",
    GMail: "😅",
    SB: "—",
    DCM: "😅",
    KDDI: "—",
    CLDR_Short_Name: "grinning face with sweat",
  },
  {
    Number: 7,
    Code: "U+1F923",
    Browser: "🤣",
    Sample: "🤣",
    GMail: "—",
    SB: "—",
    DCM: "—",
    KDDI: "—",
    CLDR_Short_Name: "rolling on the floor laughing",
  },
  {
    Number: 8,
    Code: "U+1F602",
    Browser: "😂",
    Sample: "😂",
    GMail: "😂",
    SB: "😂",
    DCM: "—",
    KDDI: "😂",
    CLDR_Short_Name: "face with tears of joy",
  },
  {
    Number: 9,
    Code: "U+1F642",
    Browser: "🙂",
    Sample: "🙂",
    GMail: "🙂",
    SB: "—",
    DCM: "—",
    KDDI: "—",
    CLDR_Short_Name: "slightly smiling face",
  },
  {
    Number: 10,
    Code: "U+1F643",
    Browser: "🙃",
    Sample: "🙃",
    GMail: "—",
    SB: "—",
    DCM: "—",
    KDDI: "—",
    CLDR_Short_Name: "upside-down face",
  },
  {
    Number: 11,
    Code: "U+1FAE0",
    Browser: "🫠",
    Sample: "🫠",
    GMail: "—",
    SB: "—",
    DCM: "—",
    KDDI: "—",
    CLDR_Short_Name: "melting face",
  },
];
